version: '3'
services:
  pretix:
    image: pretix/standalone:stable
    ports:
      - 80:8000  # Map port 8000 in the container to port 80 on the host
    environment:
      - SITE_URL=http://159.65.94.245 
